ex1: ex1.c func.o timestamps.c 
	sudo gcc -Wall -O2 -D_REENTRANT ex1.c func.o timestamps.c -o ex1 -lpthread -lrt

ex3: ex3.c func.o timestamps.c 
	sudo gcc -Wall -O2 -D_REENTRANT ex3.c func.o timestamps.c -o ex3 -lpthread -lrt

ex4_A: ex3.c func.o timestamps.c 
	sudo gcc -Wall -O2 -D_REENTRANT ex4_A.c func.o timestamps.c -o ex4_A -lpthread -lrt

ex6: ex6.c func.o timestamps.c 
	sudo gcc -Wall -O2 -D_REENTRANT ex6.c func.o timestamps.c -o ex6 -lpthread -lrt
